### ISSUE TITLE
Add documentation of input files to Jupyter Book

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/EchoPro#111]
Add a page to the Jupyter Book documenting the input files in detail

- The [echopro_bio_input_template Google sheet](https://docs.google.com/spreadsheets/d/180h_kSTnGiBUUMOKK5z_-8Saw0R_8P3HTjUJyyBRxsE/edit#gid=0) documents the final specification for biological files
- Refer to the 2019 survey year configuration file [survey_year_2019_config.yml](https://github.com/uw-echospace/EchoPro/blob/master/config_files/survey_year_2019_config.yml), for a listing of files being used in the current version of Python EchoPro
- The Google Drive folder [2019_consolidated_files](https://drive.google.com/drive/folders/13o1z5ebn3G05kAmfAVYJ3QqNEgxL8xxw?usp=sharing) (restricted access) contains all input files necessary to run the example notebooks. These files incorporate modifications from the original input files provided the NWFSC FEAT team (Chu). These changes involve primarily column names, some file names, and the source of mappings between haul numbers and transects numbers.
- For background discussions on the biological files, see https://github.com/uw-echospace/hake-IGP/issues/1

Other relevant issues:
- #13
- https://github.com/uw-echospace/hake-IGP/issues/2
- https://github.com/uw-echospace/hake-IGP/issues/3

**Comment by emiliom** [comment]
Here is a version of [survey_year_2019_config.yml](https://github.com/uw-echospace/EchoPro/blob/master/config_files/survey_year_2019_config.yml) showing all the input files, but restructured roughly following the recommendation in #109. I implemented here a draft version of that recommendation, to make it easier to read. Note that where there are separate US & CAN files, I'm only including US files.

```yaml
biological:
  length:
    - country: US
      filename: Biological/US/2019_biodata_length.xls
      sheetname: biodata_length
  specimen:
    - country: US
      filename: Biological/US/2019_biodata_specimen_AGES.xlsx
      sheetname: biodata_specimen
  catch:
    - country: US
      filename: Biological/US/2019_biodata_catch.xls
      sheetname: biodata_catch
  haul_to_transect:
    # mapping between hauls and transects
    - country: US
      filename: Biological/US/haul_to_transect_mapping_2019.xlsx
      sheetname: Sheet1
stratification:
  strata:
    # file that relates the stratification to the Haul
    # The two stratification types are found in two sheets: "Base KS" and "INPFC"
    filename: Stratification/US_CAN strata 2019_final.xlsx
    sheetname: Base KS
  geo_strata:
    # file that defines the geographic definition of strata
    # The two stratification types are found in two sheets: "stratification1" and "INPFC"
    filename: Stratification/Stratification_geographic_Lat_2019_final.xlsx
    sheetname: stratification1
nasc:
  no_age1:
    # file that provides NASC values, which do not include age1 values
    filename: Exports/US_CAN_detailsa_2019_table2y+_ALL_final - updated.xlsx
    sheetname: Sheet1
  all_ages:
    # file that provides NASC values, which include all ages
    filename: Exports/US_CAN_detailsa_2019_table1y+_ALL_final - updated.xlsx
    sheetname: Sheet1
kriging:
  mesh:
  # Mesh filename representing the centroids of the Kriging grid
    filename: Kriging_files/Kriging_grid_files/krig_grid2_5nm_cut_centroids_2013.xlsx
    sheetname: krigedgrid2_5nm_forChu
  smoothed_contour:
    # smoothed contour used to transform the mesh points
    filename: Kriging_files/Kriging_grid_files/transformation_isobath_coordinates.xlsx
    #  filename: Kriging_files/Kriging_grid_files/Smoothing_EasyKrig.xlsx
    sheetname: Smoothing_EasyKrig
  vario_krig_para:
    filename: Kriging_files/default_vario_krig_settings_2019_US_CAN.xlsx
```
